services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=lod
      - DB_USERNAME=root
      - DB_PASSWORD=pass
      - PHP_INI_DIR=/usr/local/etc/php
    depends_on:
      - mariadb
    networks:
      - app-network
    
  mariadb:
    image: mariadb:10.11
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=lod
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=pass
    networks:
      - app-network
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=pass
    depends_on:
      - mariadb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data: